/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.Toolkit;
/**
 *
 * @author Lenovo
 */

public class EscalaFaxina extends javax.swing.JFrame {

    /**
     * Creates new form EscalaFaxina
     */
    public EscalaFaxina() {
        initComponents();
        setIcon();
        
        
        panFx.setVisible(false);
        lblF4.setVisible(false);
        txtF4.setVisible(false);
        lblF5.setVisible(false);
        txtF5.setVisible(false);
        lblF6.setVisible(false);
        txtF6.setVisible(false);
        lblF7.setVisible(false);
        txtF7.setVisible(false);
        lblF8.setVisible(false);
        txtF8.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblF4 = new javax.swing.JLabel();
        lblF5 = new javax.swing.JLabel();
        lblF6 = new javax.swing.JLabel();
        txtF1 = new javax.swing.JTextField();
        txtF2 = new javax.swing.JTextField();
        txtF3 = new javax.swing.JTextField();
        txtF4 = new javax.swing.JTextField();
        txtF5 = new javax.swing.JTextField();
        txtF6 = new javax.swing.JTextField();
        lblF7 = new javax.swing.JLabel();
        txtF7 = new javax.swing.JTextField();
        panFx = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblFx1 = new javax.swing.JLabel();
        lblFx2 = new javax.swing.JLabel();
        lblFx3 = new javax.swing.JLabel();
        lblFx4 = new javax.swing.JLabel();
        lblFx5 = new javax.swing.JLabel();
        lblFx6 = new javax.swing.JLabel();
        lblFx7 = new javax.swing.JLabel();
        lblFx8 = new javax.swing.JLabel();
        lblFx9 = new javax.swing.JLabel();
        lblFx10 = new javax.swing.JLabel();
        lblFx11 = new javax.swing.JLabel();
        lblFx12 = new javax.swing.JLabel();
        lblFx13 = new javax.swing.JLabel();
        lblFx14 = new javax.swing.JLabel();
        lblFx15 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblF8 = new javax.swing.JLabel();
        txtF8 = new javax.swing.JTextField();
        btnFx = new javax.swing.JButton();
        spnC = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Escala de faxina do hangar 01");
        setResizable(false);

        jLabel1.setText("Militar 01");

        jLabel2.setText("Militar 02");

        jLabel3.setText("Militar 03");

        lblF4.setText("Militar 04");

        lblF5.setText("Militar 05 ");

        lblF6.setText("Militar 06");

        txtF5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtF5ActionPerformed(evt);
            }
        });

        lblF7.setText("Militar 07");

        panFx.setBackground(new java.awt.Color(204, 255, 204));
        panFx.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panFx.setToolTipText("");
        panFx.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N

        jLabel11.setText("SEG");

        jLabel12.setText("TER");

        jLabel13.setText("QUA");

        jLabel14.setText("QUI");

        jLabel16.setText("Banheiro:");

        jLabel17.setText("Copa:");

        jLabel18.setText("Hangar:");

        lblFx1.setText("jLabel10");

        lblFx2.setText("jLabel19");

        lblFx3.setText("jLabel20");

        lblFx4.setText("jLabel21");

        lblFx5.setText("jLabel22");

        lblFx6.setText("jLabel23");

        lblFx7.setText("jLabel24");

        lblFx8.setText("jLabel25");

        lblFx9.setText("jLabel26");

        lblFx10.setText("jLabel27");

        lblFx11.setText("jLabel28");

        lblFx12.setText("jLabel29");

        lblFx13.setText("jLabel30");

        lblFx14.setText("jLabel31");

        lblFx15.setText("jLabel32");

        jLabel15.setText("SEX");

        javax.swing.GroupLayout panFxLayout = new javax.swing.GroupLayout(panFx);
        panFx.setLayout(panFxLayout);
        panFxLayout.setHorizontalGroup(
            panFxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panFxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(27, 27, 27)
                .addGroup(panFxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(lblFx1)
                    .addComponent(lblFx2)
                    .addComponent(lblFx3))
                .addGap(44, 44, 44)
                .addGroup(panFxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(lblFx5)
                    .addComponent(lblFx4)
                    .addComponent(lblFx6))
                .addGap(46, 46, 46)
                .addGroup(panFxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(lblFx8)
                    .addComponent(lblFx7)
                    .addComponent(lblFx9))
                .addGap(50, 50, 50)
                .addGroup(panFxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFx10)
                    .addComponent(jLabel14)
                    .addComponent(lblFx11)
                    .addComponent(lblFx12))
                .addGap(41, 41, 41)
                .addGroup(panFxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFx15)
                    .addComponent(lblFx14)
                    .addComponent(jLabel15)
                    .addComponent(lblFx13))
                .addGap(19, 19, 19))
        );
        panFxLayout.setVerticalGroup(
            panFxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panFxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(panFxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lblFx1)
                    .addComponent(lblFx4)
                    .addComponent(lblFx7)
                    .addComponent(lblFx10)
                    .addComponent(lblFx13))
                .addGap(28, 28, 28)
                .addGroup(panFxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(lblFx2)
                    .addComponent(lblFx5)
                    .addComponent(lblFx8)
                    .addComponent(lblFx11)
                    .addComponent(lblFx14))
                .addGap(28, 28, 28)
                .addGroup(panFxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(lblFx3)
                    .addComponent(lblFx6)
                    .addComponent(lblFx9)
                    .addComponent(lblFx12)
                    .addComponent(lblFx15))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel8.setText("Numero de soldados na semana");

        lblF8.setText("Militar 08");

        btnFx.setBackground(new java.awt.Color(0, 153, 51));
        btnFx.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnFx.setForeground(new java.awt.Color(255, 255, 255));
        btnFx.setText("Executar");
        btnFx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFxActionPerformed(evt);
            }
        });

        spnC.setModel(new javax.swing.SpinnerNumberModel(3, 3, 8, 1));
        spnC.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnCStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(6, 6, 6)
                                .addComponent(txtF2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(586, 586, 586)
                                .addComponent(spnC, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(6, 6, 6)
                                .addComponent(txtF3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(566, 566, 566)
                                .addComponent(btnFx))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(6, 6, 6)
                                .addComponent(txtF1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(507, 507, 507)
                                .addComponent(jLabel8))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblF4)
                                .addGap(6, 6, 6)
                                .addComponent(txtF4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblF6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtF6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblF5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtF5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblF7)
                                .addGap(3, 3, 3)
                                .addComponent(txtF7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblF8)
                                .addGap(6, 6, 6)
                                .addComponent(txtF8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panFx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel1))
                            .addComponent(txtF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(spnC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(txtF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnFx))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblF4)
                    .addComponent(txtF4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblF5)
                            .addComponent(txtF5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtF6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblF6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblF7))
                            .addComponent(txtF7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblF8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtF8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(panFx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFxActionPerformed
        // TODO add your handling code here:
        Object v = spnC.getValue();
        panFx.setVisible(true);
        if(v.equals(3)){
            String nome1 = (txtF1.getText());
            String nome2 = (txtF2.getText());
            String nome3 = (txtF3.getText());
            lblFx1.setText(nome1);
            lblFx2.setText(nome2);
            lblFx3.setText(nome3);
            lblFx4.setText(nome3);
            lblFx5.setText(nome2);
            lblFx6.setText(nome1);
            lblFx7.setText(nome2);
            lblFx8.setText(nome3);
            lblFx9.setText(nome1);
            lblFx10.setText(nome1);
            lblFx11.setText(nome2);
            lblFx12.setText(nome3);
            lblFx13.setText(nome3);
            lblFx14.setText(nome1);
            lblFx15.setText(nome2);
        }
        if(v.equals(4)){
                String nome1 = (txtF1.getText());
                String nome2 = (txtF2.getText());
                String nome3 = (txtF3.getText());
                String nome4 = (txtF4.getText());
                lblFx1.setText(nome1);
                lblFx2.setText(nome2);
                lblFx3.setText(nome3);
                lblFx4.setText(nome4);
                lblFx5.setText(nome1);
                lblFx6.setText(nome2);
                lblFx7.setText(nome3);
                lblFx8.setText(nome4);
                lblFx9.setText(nome1);
                lblFx10.setText(nome2);
                lblFx11.setText(nome3);
                lblFx12.setText(nome4);
                lblFx13.setText(nome1);
                lblFx14.setText(nome2);
                lblFx15.setText(nome3);
        }
        if(v.equals(5)){
                String nome1 = (txtF1.getText());
                String nome2 = (txtF2.getText());
                String nome3 = (txtF3.getText());
                String nome4 = (txtF4.getText());
                String nome5 = (txtF5.getText());
                lblFx1.setText(nome1);
                lblFx2.setText(nome2);
                lblFx3.setText(nome3);
                lblFx4.setText(nome4);
                lblFx5.setText(nome5);
                lblFx6.setText(nome1);
                lblFx7.setText(nome2);
                lblFx8.setText(nome3);
                lblFx9.setText(nome4);
                lblFx10.setText(nome5);
                lblFx11.setText(nome1);
                lblFx12.setText(nome2);
                lblFx13.setText(nome3);
                lblFx14.setText(nome4);
                lblFx15.setText(nome5);
        }
        if(v.equals(6)){
                String nome1 = (txtF1.getText());
                String nome2 = (txtF2.getText());
                String nome3 = (txtF3.getText());
                String nome4 = (txtF4.getText());
                String nome5 = (txtF5.getText());
                String nome6 = (txtF6.getText());
                lblFx1.setText(nome1);
                lblFx2.setText(nome2);
                lblFx3.setText(nome3);
                lblFx4.setText(nome4);
                lblFx5.setText(nome5);
                lblFx6.setText(nome6);
                lblFx7.setText(nome1);
                lblFx8.setText(nome2);
                lblFx9.setText(nome3);
                lblFx10.setText(nome4);
                lblFx11.setText(nome5);
                lblFx12.setText(nome6);
                lblFx13.setText(nome1);
                lblFx14.setText(nome2);
                lblFx15.setText(nome3);
            
        }
        if(v.equals(7)){
                String nome1 = (txtF1.getText());
                String nome2 = (txtF2.getText());
                String nome3 = (txtF3.getText());
                String nome4 = (txtF4.getText());
                String nome5 = (txtF5.getText());
                String nome6 = (txtF6.getText());
                String nome7 = (txtF7.getText());
                lblFx1.setText(nome1);
                lblFx2.setText(nome2);
                lblFx3.setText(nome3);
                lblFx4.setText(nome4);
                lblFx5.setText(nome5);
                lblFx6.setText(nome6);
                lblFx7.setText(nome7);
                lblFx8.setText(nome1);
                lblFx9.setText(nome2);
                lblFx10.setText(nome3);
                lblFx11.setText(nome4);
                lblFx12.setText(nome5);
                lblFx13.setText(nome6);
                lblFx14.setText(nome7);
                lblFx15.setText(nome1);
        }
        if(v.equals(8)){
                String nome1 = (txtF1.getText());
                String nome2 = (txtF2.getText());
                String nome3 = (txtF3.getText());
                String nome4 = (txtF4.getText());
                String nome5 = (txtF5.getText());
                String nome6 = (txtF6.getText());
                String nome7 = (txtF7.getText());
                String nome8 = (txtF8.getText());
                lblFx1.setText(nome1);
                lblFx2.setText(nome2);
                lblFx3.setText(nome3);
                lblFx4.setText(nome4);
                lblFx5.setText(nome5);
                lblFx6.setText(nome6);
                lblFx7.setText(nome7);
                lblFx8.setText(nome8);
                lblFx9.setText(nome1);
                lblFx10.setText(nome2);
                lblFx11.setText(nome3);
                lblFx12.setText(nome4);
                lblFx13.setText(nome5);
                lblFx14.setText(nome6);
                lblFx15.setText(nome7);
        }
        
            
                 
            
        
        
    }//GEN-LAST:event_btnFxActionPerformed
    
    
    private void spnCStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnCStateChanged
        // TODO add your handling code here:
      
        int n1 = (int) spnC.getValue();
        if(n1 == 3){
            txtF4.setVisible(false);
            lblF4.setVisible(false);
            txtF5.setVisible(false);
            lblF5.setVisible(false);
            txtF6.setVisible(false);
            lblF6.setVisible(false);
            txtF7.setVisible(false);
            lblF7.setVisible(false);
            txtF8.setVisible(false);
            lblF8.setVisible(false);
            
        }
        if(n1 == 4){
            txtF4.setVisible(true);
            lblF4.setVisible(true);
            txtF5.setVisible(false);
            lblF5.setVisible(false);
            txtF6.setVisible(false);
            lblF6.setVisible(false);
            txtF7.setVisible(false);
            lblF7.setVisible(false);
            txtF8.setVisible(false);
            lblF8.setVisible(false);
                
        }
        if(n1 == 5){
            txtF4.setVisible(true);
            lblF4.setVisible(true);
            txtF5.setVisible(true);
            lblF5.setVisible(true);
            txtF6.setVisible(false);
            lblF6.setVisible(false);
            txtF7.setVisible(false);
            lblF7.setVisible(false);
            txtF8.setVisible(false);
            lblF8.setVisible(false);
                
        }
        if(n1 == 6){
            txtF4.setVisible(true);
            lblF4.setVisible(true);
            txtF5.setVisible(true);
            lblF5.setVisible(true);
            txtF6.setVisible(true);
            lblF6.setVisible(true);
            txtF7.setVisible(false);
            lblF7.setVisible(false);
            txtF8.setVisible(false);
            lblF8.setVisible(false);
        }        
        if(n1 == 7){
            txtF4.setVisible(true);
            lblF4.setVisible(true);
            txtF5.setVisible(true);
            lblF5.setVisible(true);
            txtF6.setVisible(true);
            lblF6.setVisible(true);
            txtF7.setVisible(true);
            lblF7.setVisible(true);
            txtF8.setVisible(false);
            lblF8.setVisible(false);
        }
        if(n1 == 8){
            txtF4.setVisible(true);
            lblF4.setVisible(true);
            txtF5.setVisible(true);
            lblF5.setVisible(true);
            txtF6.setVisible(true);
            lblF6.setVisible(true);
            txtF7.setVisible(true);
            lblF7.setVisible(true);
            txtF8.setVisible(true);
            lblF8.setVisible(true);
        }
        
        
        
        
       
    }//GEN-LAST:event_spnCStateChanged

    private void txtF5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtF5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtF5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscalaFaxina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscalaFaxina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EscalaFaxina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscalaFaxina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EscalaFaxina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblF4;
    private javax.swing.JLabel lblF5;
    private javax.swing.JLabel lblF6;
    private javax.swing.JLabel lblF7;
    private javax.swing.JLabel lblF8;
    private javax.swing.JLabel lblFx1;
    private javax.swing.JLabel lblFx10;
    private javax.swing.JLabel lblFx11;
    private javax.swing.JLabel lblFx12;
    private javax.swing.JLabel lblFx13;
    private javax.swing.JLabel lblFx14;
    private javax.swing.JLabel lblFx15;
    private javax.swing.JLabel lblFx2;
    private javax.swing.JLabel lblFx3;
    private javax.swing.JLabel lblFx4;
    private javax.swing.JLabel lblFx5;
    private javax.swing.JLabel lblFx6;
    private javax.swing.JLabel lblFx7;
    private javax.swing.JLabel lblFx8;
    private javax.swing.JLabel lblFx9;
    private javax.swing.JPanel panFx;
    private javax.swing.JSpinner spnC;
    private javax.swing.JTextField txtF1;
    private javax.swing.JTextField txtF2;
    private javax.swing.JTextField txtF3;
    private javax.swing.JTextField txtF4;
    private javax.swing.JTextField txtF5;
    private javax.swing.JTextField txtF6;
    private javax.swing.JTextField txtF7;
    private javax.swing.JTextField txtF8;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("soldier_3939761.png")));
    }
}
