
import java.awt.Dimension;
//Importando aqui dessa forma para agrupar os botões de rádio.
import javax.swing.ButtonGroup;
import java.awt.Toolkit;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lenovo
 */
public class EscalaJanela extends javax.swing.JFrame {

    /**
     * Creates new form EscalaJanela
     */
    public EscalaJanela() {
        initComponents();
        txtM5.setPreferredSize(new Dimension(78,29));
        txtM9.setPreferredSize(new Dimension(78,29));
        lblV5.setVisible(false);
        lblV6.setVisible(false);
        lblV7.setVisible(false);
        lblV8.setVisible(false);
        lblV9.setVisible(false);
        lblV10.setVisible(false);
        lblV11.setVisible(false);
        lblV12.setVisible(false);
        txtM5.setVisible(false);
        txtM6.setVisible(false);
        txtM7.setVisible(false);
        txtM8.setVisible(false);
        txtM9.setVisible(false);
        txtM10.setVisible(false);
        txtM11.setVisible(false);
        txtM12.setVisible(false);
        panEsc.setVisible(false);
        //Agrupamento dos botões de rádio
        ButtonGroup buttonGroup = new ButtonGroup();
        radInicio.setSelected(true);
        buttonGroup.add(rad5);
        buttonGroup.add(rad6);
        buttonGroup.add(rad7);
        buttonGroup.add(rad8);
        buttonGroup.add(rad9);
        buttonGroup.add(rad10);
        buttonGroup.add(rad11);
        buttonGroup.add(rad12);
        buttonGroup.add(radInicio);
        setIcon();
        
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblV5 = new javax.swing.JLabel();
        lblV6 = new javax.swing.JLabel();
        lblV7 = new javax.swing.JLabel();
        lblV8 = new javax.swing.JLabel();
        txtM1 = new javax.swing.JTextField();
        txtM2 = new javax.swing.JTextField();
        txtM3 = new javax.swing.JTextField();
        txtM4 = new javax.swing.JTextField();
        txtM5 = new javax.swing.JTextField();
        txtM6 = new javax.swing.JTextField();
        txtM7 = new javax.swing.JTextField();
        txtM8 = new javax.swing.JTextField();
        panEsc = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        lbl01 = new javax.swing.JLabel();
        lbl02 = new javax.swing.JLabel();
        lbl03 = new javax.swing.JLabel();
        lbl04 = new javax.swing.JLabel();
        lbl05 = new javax.swing.JLabel();
        lbl06 = new javax.swing.JLabel();
        lbl07 = new javax.swing.JLabel();
        lbl08 = new javax.swing.JLabel();
        lbl09 = new javax.swing.JLabel();
        lbl10 = new javax.swing.JLabel();
        lbl11 = new javax.swing.JLabel();
        lbl12 = new javax.swing.JLabel();
        lbl13 = new javax.swing.JLabel();
        lbl14 = new javax.swing.JLabel();
        lbl15 = new javax.swing.JLabel();
        lbl16 = new javax.swing.JLabel();
        lbl17 = new javax.swing.JLabel();
        lbl18 = new javax.swing.JLabel();
        lbl19 = new javax.swing.JLabel();
        lbl20 = new javax.swing.JLabel();
        lbl21 = new javax.swing.JLabel();
        lbl22 = new javax.swing.JLabel();
        lbl23 = new javax.swing.JLabel();
        lbl24 = new javax.swing.JLabel();
        lbl25 = new javax.swing.JLabel();
        lbl26 = new javax.swing.JLabel();
        lbl27 = new javax.swing.JLabel();
        lbl28 = new javax.swing.JLabel();
        lbl29 = new javax.swing.JLabel();
        lbl30 = new javax.swing.JLabel();
        lbl31 = new javax.swing.JLabel();
        lblV9 = new javax.swing.JLabel();
        lblV10 = new javax.swing.JLabel();
        lblV11 = new javax.swing.JLabel();
        lblV12 = new javax.swing.JLabel();
        txtM9 = new javax.swing.JTextField();
        txtM10 = new javax.swing.JTextField();
        txtM11 = new javax.swing.JTextField();
        txtM12 = new javax.swing.JTextField();
        rad5 = new javax.swing.JRadioButton();
        btnEx = new javax.swing.JButton();
        jLabel75 = new javax.swing.JLabel();
        rad6 = new javax.swing.JRadioButton();
        rad7 = new javax.swing.JRadioButton();
        rad8 = new javax.swing.JRadioButton();
        rad9 = new javax.swing.JRadioButton();
        rad10 = new javax.swing.JRadioButton();
        rad11 = new javax.swing.JRadioButton();
        rad12 = new javax.swing.JRadioButton();
        radInicio = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Escala de serviço com 1 por dia.");
        setResizable(false);

        jLabel1.setText("1º Militar");

        jLabel2.setText("2º Militar");

        jLabel3.setText("3º Militar");

        jLabel4.setText("4º Militar");

        lblV5.setText("5º Militar");

        lblV6.setText("6º Militar");

        lblV7.setText("7º Militar");

        lblV8.setText("8º Militar");

        panEsc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setText("01 -");

        jLabel10.setText("02 -");

        jLabel11.setText("03 -");

        jLabel12.setText("04 -");

        jLabel13.setText("05 -");

        jLabel14.setText("06 -");

        jLabel15.setText("07 -");

        jLabel16.setText("08 -");

        jLabel17.setText("09 -");

        jLabel18.setText("10 -");

        jLabel19.setText("11 -");

        jLabel20.setText("12 -");

        jLabel21.setText("13 -");

        jLabel22.setText("14 -");

        jLabel23.setText("15 -");

        jLabel24.setText("16 -");

        jLabel25.setText("17 -");

        jLabel26.setText("18 -");

        jLabel27.setText("19 -");

        jLabel28.setText("20 -");

        jLabel29.setText("21 -");

        jLabel30.setText("22 -");

        jLabel31.setText("23 -");

        jLabel32.setText("24 -");

        jLabel33.setText("25 -");

        jLabel34.setText("26 -");

        jLabel35.setText("27 -");

        jLabel36.setText("28 -");

        jLabel37.setText("29 -");

        jLabel38.setText("30 -");

        jLabel39.setText("31 -");

        lbl01.setText("jLabel44");

        lbl02.setText("jLabel45");

        lbl03.setText("jLabel46");

        lbl04.setText("jLabel47");

        lbl05.setText("jLabel48");

        lbl06.setText("jLabel49");

        lbl07.setText("jLabel50");

        lbl08.setText("jLabel51");

        lbl09.setText("jLabel52");

        lbl10.setText("jLabel53");

        lbl11.setText("jLabel54");

        lbl12.setText("jLabel55");

        lbl13.setText("jLabel56");

        lbl14.setText("jLabel57");

        lbl15.setText("jLabel58");

        lbl16.setText("jLabel59");

        lbl17.setText("jLabel60");

        lbl18.setText("jLabel61");

        lbl19.setText("jLabel62");

        lbl20.setText("jLabel63");

        lbl21.setText("jLabel64");

        lbl22.setText("jLabel65");

        lbl23.setText("jLabel66");

        lbl24.setText("jLabel67");

        lbl25.setText("jLabel68");

        lbl26.setText("jLabel69");

        lbl27.setText("jLabel70");

        lbl28.setText("jLabel71");

        lbl29.setText("jLabel72");

        lbl30.setText("jLabel73");

        lbl31.setText("jLabel74");

        javax.swing.GroupLayout panEscLayout = new javax.swing.GroupLayout(panEsc);
        panEsc.setLayout(panEscLayout);
        panEscLayout.setHorizontalGroup(
            panEscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEscLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panEscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panEscLayout.createSequentialGroup()
                        .addGroup(panEscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panEscLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl10))
                            .addGroup(panEscLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl09))
                            .addGroup(panEscLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl08))
                            .addGroup(panEscLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl07))
                            .addGroup(panEscLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl06))
                            .addGroup(panEscLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl05))
                            .addGroup(panEscLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl04))
                            .addGroup(panEscLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl03))
                            .addGroup(panEscLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl02)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panEscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(panEscLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl01)
                        .addGap(102, 102, 102)
                        .addComponent(jLabel19)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panEscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl12)
                    .addComponent(lbl13)
                    .addComponent(lbl14)
                    .addComponent(lbl15)
                    .addComponent(lbl16)
                    .addComponent(lbl17)
                    .addComponent(lbl18)
                    .addComponent(lbl19)
                    .addComponent(lbl20)
                    .addComponent(lbl11))
                .addGap(99, 99, 99)
                .addGroup(panEscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panEscLayout.createSequentialGroup()
                        .addGroup(panEscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panEscLayout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl23))
                            .addGroup(panEscLayout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl24))
                            .addGroup(panEscLayout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl25))
                            .addGroup(panEscLayout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl26))
                            .addGroup(panEscLayout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl27))
                            .addGroup(panEscLayout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl28))
                            .addGroup(panEscLayout.createSequentialGroup()
                                .addComponent(jLabel37)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl29))
                            .addGroup(panEscLayout.createSequentialGroup()
                                .addComponent(jLabel38)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl30))
                            .addGroup(panEscLayout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl22)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panEscLayout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl31)
                        .addGap(70, 70, 70))))
        );
        panEscLayout.setVerticalGroup(
            panEscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEscLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panEscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel19)
                    .addComponent(jLabel29)
                    .addComponent(jLabel39)
                    .addComponent(lbl01)
                    .addComponent(lbl11)
                    .addComponent(lbl21)
                    .addComponent(lbl31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panEscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel20)
                    .addComponent(jLabel30)
                    .addComponent(lbl02)
                    .addComponent(lbl12)
                    .addComponent(lbl22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panEscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel21)
                    .addComponent(jLabel31)
                    .addComponent(lbl03)
                    .addComponent(lbl13)
                    .addComponent(lbl23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panEscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel22)
                    .addComponent(jLabel32)
                    .addComponent(lbl04)
                    .addComponent(lbl14)
                    .addComponent(lbl24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panEscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel23)
                    .addComponent(jLabel33)
                    .addComponent(lbl05)
                    .addComponent(lbl15)
                    .addComponent(lbl25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panEscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel24)
                    .addComponent(jLabel34)
                    .addComponent(lbl06)
                    .addComponent(lbl16)
                    .addComponent(lbl26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panEscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel25)
                    .addComponent(jLabel35)
                    .addComponent(lbl07)
                    .addComponent(lbl17)
                    .addComponent(lbl27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panEscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel26)
                    .addComponent(jLabel36)
                    .addComponent(lbl08)
                    .addComponent(lbl18)
                    .addComponent(lbl28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panEscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel27)
                    .addComponent(jLabel37)
                    .addComponent(lbl09)
                    .addComponent(lbl19)
                    .addComponent(lbl29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panEscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel28)
                    .addComponent(jLabel38)
                    .addComponent(lbl10)
                    .addComponent(lbl20)
                    .addComponent(lbl30))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        lblV9.setText("9º Militar");

        lblV10.setText("10º Militar");

        lblV11.setText("11º Militar");

        lblV12.setText("12º Militar");

        rad5.setText("05 Militares");
        rad5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad5ActionPerformed(evt);
            }
        });

        btnEx.setBackground(new java.awt.Color(204, 0, 0));
        btnEx.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEx.setForeground(new java.awt.Color(255, 255, 255));
        btnEx.setText("EXECUTAR");
        btnEx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExActionPerformed(evt);
            }
        });

        jLabel75.setBackground(new java.awt.Color(255, 255, 255));
        jLabel75.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel75.setText("Militares na Escala");

        rad6.setText("06 Militares");
        rad6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad6ActionPerformed(evt);
            }
        });

        rad7.setText("07 Militares");
        rad7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad7ActionPerformed(evt);
            }
        });

        rad8.setText("08 Militares");
        rad8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad8ActionPerformed(evt);
            }
        });

        rad9.setText("09 Militares");
        rad9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad9ActionPerformed(evt);
            }
        });

        rad10.setText("10 Militares");
        rad10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad10ActionPerformed(evt);
            }
        });

        rad11.setText("11 Militares");
        rad11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad11ActionPerformed(evt);
            }
        });

        rad12.setText("12 Militares");
        rad12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad12ActionPerformed(evt);
            }
        });

        radInicio.setText("04 Militares");
        radInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radInicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(panEsc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtM1)
                            .addComponent(txtM2)
                            .addComponent(txtM3)
                            .addComponent(txtM4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblV8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblV7, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblV6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblV5, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtM7)
                            .addComponent(txtM6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtM8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtM5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblV10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblV9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblV11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblV12, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtM11)
                            .addComponent(txtM10, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtM9, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtM12, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rad5, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(rad6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(rad7, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(radInicio, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rad10, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(rad11, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(rad12))
                            .addComponent(rad8)
                            .addComponent(rad9))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel75)
                        .addGap(14, 14, 14))
                    .addComponent(btnEx))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(txtM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(txtM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(txtM3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(txtM4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblV5)
                                        .addComponent(txtM5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblV6)
                                        .addComponent(txtM6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblV7)
                                        .addComponent(txtM7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblV8)
                                        .addComponent(txtM8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblV9)
                                    .addComponent(txtM9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblV10)
                                    .addComponent(txtM10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblV11)
                                    .addComponent(txtM11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblV12)
                                    .addComponent(txtM12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(74, 74, 74)
                        .addComponent(panEsc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel75)
                        .addGap(18, 18, 18)
                        .addComponent(radInicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rad5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rad6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rad7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rad8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rad9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rad10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rad11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rad12)
                        .addGap(18, 18, 18)
                        .addComponent(btnEx)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExActionPerformed
       
        
        panEsc.setVisible(true);
        String milico1 = (txtM1.getText());
        String milico2 = (txtM2.getText());
        String milico3 = (txtM3.getText());
        String milico4 = (txtM4.getText());
        lbl01.setText(milico1);
        lbl02.setText(milico2);
        lbl03.setText(milico3);
        lbl04.setText(milico4);
        lbl05.setText(milico1);
        lbl06.setText(milico2);
        lbl07.setText(milico3);
        lbl08.setText(milico4);
        lbl09.setText(milico1);
        lbl10.setText(milico2);
        lbl11.setText(milico3);
        lbl12.setText(milico4);
        lbl13.setText(milico1);
        lbl14.setText(milico2);
        lbl15.setText(milico3);
        lbl16.setText(milico4);
        lbl17.setText(milico1);
        lbl18.setText(milico2);
        lbl19.setText(milico3);
        lbl20.setText(milico4);
        lbl21.setText(milico1);
        lbl22.setText(milico2);
        lbl23.setText(milico3);
        lbl24.setText(milico4);
        lbl25.setText(milico1);
        lbl26.setText(milico2);
        lbl27.setText(milico3);
        lbl28.setText(milico4);
        lbl29.setText(milico1);
        lbl30.setText(milico2);
        lbl31.setText(milico3);
        if (rad5.isSelected()){
            String milico5 = (txtM5.getText());
        lbl01.setText(milico1);
        lbl02.setText(milico2);
        lbl03.setText(milico3);
        lbl04.setText(milico4);
        lbl05.setText(milico5);
        lbl06.setText(milico1);
        lbl07.setText(milico2);
        lbl08.setText(milico3);
        lbl09.setText(milico4);
        lbl10.setText(milico5);
        lbl11.setText(milico1);
        lbl12.setText(milico2);
        lbl13.setText(milico3);
        lbl14.setText(milico4);
        lbl15.setText(milico5);
        lbl16.setText(milico1);
        lbl17.setText(milico2);
        lbl18.setText(milico3);
        lbl19.setText(milico4);
        lbl20.setText(milico5);
        lbl21.setText(milico1);
        lbl22.setText(milico2);
        lbl23.setText(milico3);
        lbl24.setText(milico4);
        lbl25.setText(milico5);
        lbl26.setText(milico1);
        lbl27.setText(milico2);
        lbl28.setText(milico3);
        lbl29.setText(milico4);
        lbl30.setText(milico5);
        lbl31.setText(milico1);
        }
        
        if (rad6.isSelected()){
            String milico5 = (txtM5.getText());
            String milico6 = (txtM6.getText());
        lbl01.setText(milico1);
        lbl02.setText(milico2);
        lbl03.setText(milico3);
        lbl04.setText(milico4);
        lbl05.setText(milico5);
        lbl06.setText(milico6);
        lbl07.setText(milico1);
        lbl08.setText(milico2);
        lbl09.setText(milico3);
        lbl10.setText(milico4);
        lbl11.setText(milico5);
        lbl12.setText(milico6);
        lbl13.setText(milico1);
        lbl14.setText(milico2);
        lbl15.setText(milico3);
        lbl16.setText(milico4);
        lbl17.setText(milico5);
        lbl18.setText(milico6);
        lbl19.setText(milico1);
        lbl20.setText(milico2);
        lbl21.setText(milico3);
        lbl22.setText(milico4);
        lbl23.setText(milico5);
        lbl24.setText(milico6);
        lbl25.setText(milico1);
        lbl26.setText(milico2);
        lbl27.setText(milico3);
        lbl28.setText(milico4);
        lbl29.setText(milico5);
        lbl30.setText(milico6);
        lbl31.setText(milico1);
        }
        if (rad7.isSelected()){
            String milico5 = (txtM5.getText());
            String milico6 = (txtM6.getText());
            String milico7 = (txtM7.getText());
        lbl01.setText(milico1);
        lbl02.setText(milico2);
        lbl03.setText(milico3);
        lbl04.setText(milico4);
        lbl05.setText(milico5);
        lbl06.setText(milico1);
        lbl07.setText(milico2);
        lbl08.setText(milico3);
        lbl09.setText(milico4);
        lbl10.setText(milico5);
        lbl11.setText(milico6);
        lbl12.setText(milico7);
        lbl13.setText(milico3);
        lbl14.setText(milico4);
        lbl15.setText(milico5);
        lbl16.setText(milico6);
        lbl17.setText(milico7);
        lbl18.setText(milico1);
        lbl19.setText(milico2);
        lbl20.setText(milico5);
        lbl21.setText(milico6);
        lbl22.setText(milico7);
        lbl23.setText(milico1);
        lbl24.setText(milico2);
        lbl25.setText(milico3);
        lbl26.setText(milico4);
        lbl27.setText(milico7);
        lbl28.setText(milico1);
        lbl29.setText(milico2);
        lbl30.setText(milico3);
        lbl31.setText(milico4);
        }
        if (rad8.isSelected()){
            String milico5 = (txtM5.getText());
            String milico6 = (txtM6.getText());
            String milico7 = (txtM7.getText());
            String milico8 = (txtM8.getText());
        lbl01.setText(milico1);
        lbl02.setText(milico2);
        lbl03.setText(milico3);
        lbl04.setText(milico4);
        lbl05.setText(milico5);
        lbl06.setText(milico6);
        lbl07.setText(milico7);
        lbl08.setText(milico8);
        lbl09.setText(milico1);
        lbl10.setText(milico2);
        lbl11.setText(milico3);
        lbl12.setText(milico4);
        lbl13.setText(milico5);
        lbl14.setText(milico6);
        lbl15.setText(milico7);
        lbl16.setText(milico8);
        lbl17.setText(milico1);
        lbl18.setText(milico2);
        lbl19.setText(milico3);
        lbl20.setText(milico4);
        lbl21.setText(milico5);
        lbl22.setText(milico6);
        lbl23.setText(milico7);
        lbl24.setText(milico8);
        lbl25.setText(milico1);
        lbl26.setText(milico2);
        lbl27.setText(milico3);
        lbl28.setText(milico4);
        lbl29.setText(milico5);
        lbl30.setText(milico6);
        lbl31.setText(milico7);
        }
        if (rad9.isSelected()){
            String milico5 = (txtM5.getText());
            String milico6 = (txtM6.getText());
            String milico7 = (txtM7.getText());
            String milico8 = (txtM8.getText());
            String milico9 = (txtM9.getText());
        lbl01.setText(milico1);
        lbl02.setText(milico2);
        lbl03.setText(milico3);
        lbl04.setText(milico4);
        lbl05.setText(milico5);
        lbl06.setText(milico6);
        lbl07.setText(milico7);
        lbl08.setText(milico8);
        lbl09.setText(milico9);
        lbl10.setText(milico1);
        lbl11.setText(milico2);
        lbl12.setText(milico3);
        lbl13.setText(milico4);
        lbl14.setText(milico5);
        lbl15.setText(milico6);
        lbl16.setText(milico7);
        lbl17.setText(milico8);
        lbl18.setText(milico9);
        lbl19.setText(milico1);
        lbl20.setText(milico2);
        lbl21.setText(milico3);
        lbl22.setText(milico4);
        lbl23.setText(milico5);
        lbl24.setText(milico6);
        lbl25.setText(milico7);
        lbl26.setText(milico8);
        lbl27.setText(milico9);
        lbl28.setText(milico1);
        lbl29.setText(milico2);
        lbl30.setText(milico3);
        lbl31.setText(milico4);
        }
        if (rad10.isSelected()){
            String milico5 = (txtM5.getText());
            String milico6 = (txtM6.getText());
            String milico7 = (txtM7.getText());
            String milico8 = (txtM8.getText());
            String milico9 = (txtM9.getText());
            String milico10 = (txtM10.getText());
        lbl01.setText(milico1);
        lbl02.setText(milico2);
        lbl03.setText(milico3);
        lbl04.setText(milico4);
        lbl05.setText(milico5);
        lbl06.setText(milico6);
        lbl07.setText(milico7);
        lbl08.setText(milico8);
        lbl09.setText(milico9);
        lbl10.setText(milico10);
        lbl11.setText(milico1);
        lbl12.setText(milico2);
        lbl13.setText(milico3);
        lbl14.setText(milico4);
        lbl15.setText(milico5);
        lbl16.setText(milico6);
        lbl17.setText(milico7);
        lbl18.setText(milico8);
        lbl19.setText(milico9);
        lbl20.setText(milico10);
        lbl21.setText(milico1);
        lbl22.setText(milico2);
        lbl23.setText(milico3);
        lbl24.setText(milico4);
        lbl25.setText(milico5);
        lbl26.setText(milico6);
        lbl27.setText(milico7);
        lbl28.setText(milico8);
        lbl29.setText(milico9);
        lbl30.setText(milico10);
        lbl31.setText(milico1);
        }
        if (rad11.isSelected()){
            String milico5 = (txtM5.getText());
            String milico6 = (txtM6.getText());
            String milico7 = (txtM7.getText());
            String milico8 = (txtM8.getText());
            String milico9 = (txtM9.getText());
            String milico10 = (txtM10.getText());
            String milico11 = (txtM11.getText());
        lbl01.setText(milico1);
        lbl02.setText(milico2);
        lbl03.setText(milico3);
        lbl04.setText(milico4);
        lbl05.setText(milico5);
        lbl06.setText(milico6);
        lbl07.setText(milico7);
        lbl08.setText(milico8);
        lbl09.setText(milico9);
        lbl10.setText(milico10);
        lbl11.setText(milico11);
        lbl12.setText(milico1);
        lbl13.setText(milico2);
        lbl14.setText(milico3);
        lbl15.setText(milico4);
        lbl16.setText(milico5);
        lbl17.setText(milico6);
        lbl18.setText(milico7);
        lbl19.setText(milico8);
        lbl20.setText(milico9);
        lbl21.setText(milico10);
        lbl22.setText(milico11);
        lbl23.setText(milico1);
        lbl24.setText(milico2);
        lbl25.setText(milico3);
        lbl26.setText(milico4);
        lbl27.setText(milico5);
        lbl28.setText(milico6);
        lbl29.setText(milico7);
        lbl30.setText(milico8);
        lbl31.setText(milico9);
        }
        if (rad12.isSelected()){
            String milico5 = (txtM5.getText());
            String milico6 = (txtM6.getText());
            String milico7 = (txtM7.getText());
            String milico8 = (txtM8.getText());
            String milico9 = (txtM9.getText());
            String milico10 = (txtM10.getText());
            String milico11 = (txtM11.getText());
            String milico12 = (txtM12.getText());
        lbl01.setText(milico1);
        lbl02.setText(milico2);
        lbl03.setText(milico3);
        lbl04.setText(milico4);
        lbl05.setText(milico5);
        lbl06.setText(milico6);
        lbl07.setText(milico7);
        lbl08.setText(milico8);
        lbl09.setText(milico9);
        lbl10.setText(milico10);
        lbl11.setText(milico11);
        lbl12.setText(milico12);
        lbl13.setText(milico1);
        lbl14.setText(milico2);
        lbl15.setText(milico3);
        lbl16.setText(milico4);
        lbl17.setText(milico5);
        lbl18.setText(milico6);
        lbl19.setText(milico7);
        lbl20.setText(milico8);
        lbl21.setText(milico9);
        lbl22.setText(milico10);
        lbl23.setText(milico11);
        lbl24.setText(milico12);
        lbl25.setText(milico1);
        lbl26.setText(milico2);
        lbl27.setText(milico3);
        lbl28.setText(milico4);
        lbl29.setText(milico5);
        lbl30.setText(milico6);
        lbl31.setText(milico7);
        }
        
        
       
        
       
            
        
        
    }//GEN-LAST:event_btnExActionPerformed

    private void rad5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad5ActionPerformed
        lblV5.setVisible(true);
        txtM5.setVisible(true);       
        lblV6.setVisible(false);
        txtM6.setVisible(false);
        lblV7.setVisible(false);
        txtM7.setVisible(false);
        lblV8.setVisible(false);
        txtM8.setVisible(false);
        lblV9.setVisible(false);
        txtM9.setVisible(false);
        lblV10.setVisible(false);
        txtM10.setVisible(false);      
        lblV11.setVisible(false);
        txtM11.setVisible(false);
        lblV12.setVisible(false);
        txtM12.setVisible(false);
        if(!rad5.isSelected()){
            
            String milico1 = (txtM1.getText());
            String milico2 = (txtM2.getText());
            String milico3 = (txtM3.getText());
            String milico4 = (txtM4.getText());
            lbl01.setText(milico1);
            lbl02.setText(milico2);
            lbl03.setText(milico3);
            lbl04.setText(milico4);
            lbl05.setText(milico1);
            lbl06.setText(milico2);
            lbl07.setText(milico3);
            lbl08.setText(milico4);
            lbl09.setText(milico1);
            lbl10.setText(milico2);
            lbl11.setText(milico3);
            lbl12.setText(milico4);
            lbl13.setText(milico1);
            lbl14.setText(milico2);
            lbl15.setText(milico3);
            lbl16.setText(milico4);
            lbl17.setText(milico1);
            lbl18.setText(milico2);
            lbl19.setText(milico3);
            lbl20.setText(milico4);
            lbl21.setText(milico1);
            lbl22.setText(milico2);
            lbl23.setText(milico3);
            lbl24.setText(milico4);
            lbl25.setText(milico1);
            lbl26.setText(milico2);
            lbl27.setText(milico3);
            lbl28.setText(milico4);
            lbl29.setText(milico1);
            lbl30.setText(milico2);
            lbl31.setText(milico3);
        }
        
       
        
        
    }//GEN-LAST:event_rad5ActionPerformed

    private void rad6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad6ActionPerformed
        // TODO add your handling code here:
        lblV5.setVisible(true);
        txtM5.setVisible(true);       
        lblV6.setVisible(true);
        txtM6.setVisible(true);
        lblV7.setVisible(false);
        txtM7.setVisible(false);
        lblV8.setVisible(false);
        txtM8.setVisible(false);
        lblV9.setVisible(false);
        txtM9.setVisible(false);
        lblV10.setVisible(false);
        txtM10.setVisible(false);      
        lblV11.setVisible(false);
        txtM11.setVisible(false);
        lblV12.setVisible(false);
        txtM12.setVisible(false);
        if(!rad6.isSelected()){
           String milico1 = (txtM1.getText());
           String milico2 = (txtM2.getText());
           String milico3 = (txtM3.getText());
           String milico4 = (txtM4.getText());
            
            
            lbl01.setText(milico1);
            lbl02.setText(milico2);
            lbl03.setText(milico3);
            lbl04.setText(milico4);
            lbl05.setText(milico1);
            lbl06.setText(milico2);
            lbl07.setText(milico3);
            lbl08.setText(milico4);
            lbl09.setText(milico1);
            lbl10.setText(milico2);
            lbl11.setText(milico3);
            lbl12.setText(milico4);
            lbl13.setText(milico1);
            lbl14.setText(milico2);
            lbl15.setText(milico3);
            lbl16.setText(milico4);
            lbl17.setText(milico1);
            lbl18.setText(milico2);
            lbl19.setText(milico3);
            lbl20.setText(milico4);
            lbl21.setText(milico1);
            lbl22.setText(milico2);
            lbl23.setText(milico3);
            lbl24.setText(milico4);
            lbl25.setText(milico1);
            lbl26.setText(milico2);
            lbl27.setText(milico3);
            lbl28.setText(milico4);
            lbl29.setText(milico1);
            lbl30.setText(milico2);
            lbl31.setText(milico3);
            
            
        
    }                       
    }//GEN-LAST:event_rad6ActionPerformed

    private void rad7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad7ActionPerformed
        // TODO add your handling code here:
        lblV5.setVisible(true);
        txtM5.setVisible(true);       
        lblV6.setVisible(true);
        txtM6.setVisible(true);
        lblV7.setVisible(true);
        txtM7.setVisible(true);
        lblV8.setVisible(false);
        txtM8.setVisible(false);
        lblV9.setVisible(false);
        txtM9.setVisible(false);
        lblV10.setVisible(false);
        txtM10.setVisible(false);      
        lblV11.setVisible(false);
        txtM11.setVisible(false);
        lblV12.setVisible(false);
        txtM12.setVisible(false);
        
        if(!rad7.isSelected()){
            
            
            
            String milico1 = (txtM1.getText());
            String milico2 = (txtM2.getText());
            String milico3 = (txtM3.getText());
            String milico4 = (txtM4.getText());
            lbl01.setText(milico1);
            lbl02.setText(milico2);
            lbl03.setText(milico3);
            lbl04.setText(milico4);
            lbl05.setText(milico1);
            lbl06.setText(milico2);
            lbl07.setText(milico3);
            lbl08.setText(milico4);
            lbl09.setText(milico1);
            lbl10.setText(milico2);
            lbl11.setText(milico3);
            lbl12.setText(milico4);
            lbl13.setText(milico1);
            lbl14.setText(milico2);
            lbl15.setText(milico3);
            lbl16.setText(milico4);
            lbl17.setText(milico1);
            lbl18.setText(milico2);
            lbl19.setText(milico3);
            lbl20.setText(milico4);
            lbl21.setText(milico1);
            lbl22.setText(milico2);
            lbl23.setText(milico3);
            lbl24.setText(milico4);
            lbl25.setText(milico1);
            lbl26.setText(milico2);
            lbl27.setText(milico3);
            lbl28.setText(milico4);
            lbl29.setText(milico1);
            lbl30.setText(milico2);
            lbl31.setText(milico3);
    }
    }//GEN-LAST:event_rad7ActionPerformed

    private void rad8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad8ActionPerformed
        // TODO add your handling code here:
        lblV5.setVisible(true);
        txtM5.setVisible(true);       
        lblV6.setVisible(true);
        txtM6.setVisible(true);
        lblV7.setVisible(true);
        txtM7.setVisible(true);
        lblV8.setVisible(true);
        txtM8.setVisible(true);
        lblV9.setVisible(false);
        txtM9.setVisible(false);
        lblV10.setVisible(false);
        txtM10.setVisible(false);      
        lblV11.setVisible(false);
        txtM11.setVisible(false);
        lblV12.setVisible(false);
        txtM12.setVisible(false);
        if(!rad8.isSelected()){
            
            String milico1 = (txtM1.getText());
            String milico2 = (txtM2.getText());
            String milico3 = (txtM3.getText());
            String milico4 = (txtM4.getText());
            lbl01.setText(milico1);
            lbl02.setText(milico2);
            lbl03.setText(milico3);
            lbl04.setText(milico4);
            lbl05.setText(milico1);
            lbl06.setText(milico2);
            lbl07.setText(milico3);
            lbl08.setText(milico4);
            lbl09.setText(milico1);
            lbl10.setText(milico2);
            lbl11.setText(milico3);
            lbl12.setText(milico4);
            lbl13.setText(milico1);
            lbl14.setText(milico2);
            lbl15.setText(milico3);
            lbl16.setText(milico4);
            lbl17.setText(milico1);
            lbl18.setText(milico2);
            lbl19.setText(milico3);
            lbl20.setText(milico4);
            lbl21.setText(milico1);
            lbl22.setText(milico2);
            lbl23.setText(milico3);
            lbl24.setText(milico4);
            lbl25.setText(milico1);
            lbl26.setText(milico2);
            lbl27.setText(milico3);
            lbl28.setText(milico4);
            lbl29.setText(milico1);
            lbl30.setText(milico2);
            lbl31.setText(milico3);
    }
    }//GEN-LAST:event_rad8ActionPerformed

    private void rad9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad9ActionPerformed
        // TODO add your handling code here:
        lblV5.setVisible(true);
        txtM5.setVisible(true);       
        lblV6.setVisible(true);
        txtM6.setVisible(true);
        lblV7.setVisible(true);
        txtM7.setVisible(true);
        lblV8.setVisible(true);
        txtM8.setVisible(true);
        lblV9.setVisible(true);
        txtM9.setVisible(true);
        lblV10.setVisible(false);
        txtM10.setVisible(false);      
        lblV11.setVisible(false);
        txtM11.setVisible(false);
        lblV12.setVisible(false);
        txtM12.setVisible(false);
        if(!rad9.isSelected()){
           String milico1 = (txtM1.getText());
           String milico2 = (txtM2.getText());
           String milico3 = (txtM3.getText());
           String milico4 = (txtM4.getText());
            
            
            lbl01.setText(milico1);
            lbl02.setText(milico2);
            lbl03.setText(milico3);
            lbl04.setText(milico4);
            lbl05.setText(milico1);
            lbl06.setText(milico2);
            lbl07.setText(milico3);
            lbl08.setText(milico4);
            lbl09.setText(milico1);
            lbl10.setText(milico2);
            lbl11.setText(milico3);
            lbl12.setText(milico4);
            lbl13.setText(milico1);
            lbl14.setText(milico2);
            lbl15.setText(milico3);
            lbl16.setText(milico4);
            lbl17.setText(milico1);
            lbl18.setText(milico2);
            lbl19.setText(milico3);
            lbl20.setText(milico4);
            lbl21.setText(milico1);
            lbl22.setText(milico2);
            lbl23.setText(milico3);
            lbl24.setText(milico4);
            lbl25.setText(milico1);
            lbl26.setText(milico2);
            lbl27.setText(milico3);
            lbl28.setText(milico4);
            lbl29.setText(milico1);
            lbl30.setText(milico2);
            lbl31.setText(milico3);
    }
    }//GEN-LAST:event_rad9ActionPerformed

    private void rad10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad10ActionPerformed
        // TODO add your handling code here:
        lblV5.setVisible(true);
        txtM5.setVisible(true);       
        lblV6.setVisible(true);
        txtM6.setVisible(true);
        lblV7.setVisible(true);
        txtM7.setVisible(true);
        lblV8.setVisible(true);
        txtM8.setVisible(true);
        lblV9.setVisible(true);
        txtM9.setVisible(true);
        lblV10.setVisible(true);
        txtM10.setVisible(true);      
        lblV11.setVisible(false);
        txtM11.setVisible(false);
        lblV12.setVisible(false);
        txtM12.setVisible(false);
        if(!rad10.isSelected()){
            String milico1 = (txtM1.getText());
            String milico2 = (txtM2.getText());
            String milico3 = (txtM3.getText());
            String milico4 = (txtM4.getText());

            
            lbl01.setText(milico1);
            lbl02.setText(milico2);
            lbl03.setText(milico3);
            lbl04.setText(milico4);
            lbl05.setText(milico1);
            lbl06.setText(milico2);
            lbl07.setText(milico3);
            lbl08.setText(milico4);
            lbl09.setText(milico1);
            lbl10.setText(milico2);
            lbl11.setText(milico3);
            lbl12.setText(milico4);
            lbl13.setText(milico1);
            lbl14.setText(milico2);
            lbl15.setText(milico3);
            lbl16.setText(milico4);
            lbl17.setText(milico1);
            lbl18.setText(milico2);
            lbl19.setText(milico3);
            lbl20.setText(milico4);
            lbl21.setText(milico1);
            lbl22.setText(milico2);
            lbl23.setText(milico3);
            lbl24.setText(milico4);
            lbl25.setText(milico1);
            lbl26.setText(milico2);
            lbl27.setText(milico3);
            lbl28.setText(milico4);
            lbl29.setText(milico1);
            lbl30.setText(milico2);
            lbl31.setText(milico3);
        }
    }//GEN-LAST:event_rad10ActionPerformed

    private void rad11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad11ActionPerformed
        // TODO add your handling code here:
        lblV5.setVisible(true);
        txtM5.setVisible(true);       
        lblV6.setVisible(true);
        txtM6.setVisible(true);
        lblV7.setVisible(true);
        txtM7.setVisible(true);
        lblV8.setVisible(true);
        txtM8.setVisible(true);
        lblV9.setVisible(true);
        txtM9.setVisible(true);
        lblV10.setVisible(true);
        txtM10.setVisible(true);      
        lblV11.setVisible(true);
        txtM11.setVisible(true);
        lblV12.setVisible(false);
        txtM12.setVisible(false);
        if(!rad11.isSelected()){
           String milico1 = (txtM1.getText());
           String milico2 = (txtM2.getText());
           String milico3 = (txtM3.getText());
           String milico4 = (txtM4.getText());
            
            
            lbl01.setText(milico1);
            lbl02.setText(milico2);
            lbl03.setText(milico3);
            lbl04.setText(milico4);
            lbl05.setText(milico1);
            lbl06.setText(milico2);
            lbl07.setText(milico3);
            lbl08.setText(milico4);
            lbl09.setText(milico1);
            lbl10.setText(milico2);
            lbl11.setText(milico3);
            lbl12.setText(milico4);
            lbl13.setText(milico1);
            lbl14.setText(milico2);
            lbl15.setText(milico3);
            lbl16.setText(milico4);
            lbl17.setText(milico1);
            lbl18.setText(milico2);
            lbl19.setText(milico3);
            lbl20.setText(milico4);
            lbl21.setText(milico1);
            lbl22.setText(milico2);
            lbl23.setText(milico3);
            lbl24.setText(milico4);
            lbl25.setText(milico1);
            lbl26.setText(milico2);
            lbl27.setText(milico3);
            lbl28.setText(milico4);
            lbl29.setText(milico1);
            lbl30.setText(milico2);
            lbl31.setText(milico3);
    }
    }//GEN-LAST:event_rad11ActionPerformed

    private void rad12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad12ActionPerformed
        // TODO add your handling code here:
        lblV5.setVisible(true);
        txtM5.setVisible(true);
        lblV6.setVisible(true);
        txtM6.setVisible(true);
        lblV7.setVisible(true);
        txtM7.setVisible(true);
        lblV8.setVisible(true);
        txtM8.setVisible(true);
        lblV9.setVisible(true);
        txtM9.setVisible(true);
        lblV10.setVisible(true);
        txtM10.setVisible(true);
        lblV11.setVisible(true);
        txtM11.setVisible(true);
        lblV12.setVisible(true);
        txtM12.setVisible(true);
        if(!rad12.isSelected()){
           String milico1 = (txtM1.getText());
           String milico2 = (txtM2.getText());
           String milico3 = (txtM3.getText());
           String milico4 = (txtM4.getText());
            
            
            lbl01.setText(milico1);
            lbl02.setText(milico2);
            lbl03.setText(milico3);
            lbl04.setText(milico4);
            lbl05.setText(milico1);
            lbl06.setText(milico2);
            lbl07.setText(milico3);
            lbl08.setText(milico4);
            lbl09.setText(milico1);
            lbl10.setText(milico2);
            lbl11.setText(milico3);
            lbl12.setText(milico4);
            lbl13.setText(milico1);
            lbl14.setText(milico2);
            lbl15.setText(milico3);
            lbl16.setText(milico4);
            lbl17.setText(milico1);
            lbl18.setText(milico2);
            lbl19.setText(milico3);
            lbl20.setText(milico4);
            lbl21.setText(milico1);
            lbl22.setText(milico2);
            lbl23.setText(milico3);
            lbl24.setText(milico4);
            lbl25.setText(milico1);
            lbl26.setText(milico2);
            lbl27.setText(milico3);
            lbl28.setText(milico4);
            lbl29.setText(milico1);
            lbl30.setText(milico2);
            lbl31.setText(milico3);
    }
    }//GEN-LAST:event_rad12ActionPerformed

    private void radInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radInicioActionPerformed
        // TODO add your handling code here:
        lblV5.setVisible(false);
        txtM5.setVisible(false);       
        lblV6.setVisible(false);
        txtM6.setVisible(false);
        lblV7.setVisible(false);
        txtM7.setVisible(false);
        lblV8.setVisible(false);
        txtM8.setVisible(false);
        lblV9.setVisible(false);
        txtM9.setVisible(false);
        lblV10.setVisible(false);
        txtM10.setVisible(false);      
        lblV11.setVisible(false);
        txtM11.setVisible(false);
        lblV12.setVisible(false);
        txtM12.setVisible(false);
    }//GEN-LAST:event_radInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscalaJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscalaJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EscalaJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscalaJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(() -> {
            new EscalaJanela().setVisible(true);
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl01;
    private javax.swing.JLabel lbl02;
    private javax.swing.JLabel lbl03;
    private javax.swing.JLabel lbl04;
    private javax.swing.JLabel lbl05;
    private javax.swing.JLabel lbl06;
    private javax.swing.JLabel lbl07;
    private javax.swing.JLabel lbl08;
    private javax.swing.JLabel lbl09;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl11;
    private javax.swing.JLabel lbl12;
    private javax.swing.JLabel lbl13;
    private javax.swing.JLabel lbl14;
    private javax.swing.JLabel lbl15;
    private javax.swing.JLabel lbl16;
    private javax.swing.JLabel lbl17;
    private javax.swing.JLabel lbl18;
    private javax.swing.JLabel lbl19;
    private javax.swing.JLabel lbl20;
    private javax.swing.JLabel lbl21;
    private javax.swing.JLabel lbl22;
    private javax.swing.JLabel lbl23;
    private javax.swing.JLabel lbl24;
    private javax.swing.JLabel lbl25;
    private javax.swing.JLabel lbl26;
    private javax.swing.JLabel lbl27;
    private javax.swing.JLabel lbl28;
    private javax.swing.JLabel lbl29;
    private javax.swing.JLabel lbl30;
    private javax.swing.JLabel lbl31;
    private javax.swing.JLabel lblV10;
    private javax.swing.JLabel lblV11;
    private javax.swing.JLabel lblV12;
    private javax.swing.JLabel lblV5;
    private javax.swing.JLabel lblV6;
    private javax.swing.JLabel lblV7;
    private javax.swing.JLabel lblV8;
    private javax.swing.JLabel lblV9;
    private javax.swing.JPanel panEsc;
    private javax.swing.JRadioButton rad10;
    private javax.swing.JRadioButton rad11;
    private javax.swing.JRadioButton rad12;
    private javax.swing.JRadioButton rad5;
    private javax.swing.JRadioButton rad6;
    private javax.swing.JRadioButton rad7;
    private javax.swing.JRadioButton rad8;
    private javax.swing.JRadioButton rad9;
    private javax.swing.JRadioButton radInicio;
    private javax.swing.JTextField txtM1;
    private javax.swing.JTextField txtM10;
    private javax.swing.JTextField txtM11;
    private javax.swing.JTextField txtM12;
    private javax.swing.JTextField txtM2;
    private javax.swing.JTextField txtM3;
    private javax.swing.JTextField txtM4;
    private javax.swing.JTextField txtM5;
    private javax.swing.JTextField txtM6;
    private javax.swing.JTextField txtM7;
    private javax.swing.JTextField txtM8;
    private javax.swing.JTextField txtM9;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("soldier_3939761.png")));
    }
}
