
import java.awt.Toolkit;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lenovo
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuUm = new javax.swing.JMenu();
        menu1Nd = new javax.swing.JMenuItem();
        menuSegundo = new javax.swing.JMenuItem();
        menuDois = new javax.swing.JMenu();
        menuF = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Minhas ferramentas");
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guerra.jpg"))); // NOI18N

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));

        menuUm.setText("Escala de serviço");
        menuUm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUmActionPerformed(evt);
            }
        });

        menu1Nd.setText("Um no dia");
        menu1Nd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu1NdActionPerformed(evt);
            }
        });
        menuUm.add(menu1Nd);

        menuSegundo.setText("Dois no dia");
        menuSegundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSegundoActionPerformed(evt);
            }
        });
        menuUm.add(menuSegundo);

        jMenuBar1.add(menuUm);

        menuDois.setText("Escala de faxina");
        menuDois.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuDois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDoisActionPerformed(evt);
            }
        });

        menuF.setText("Faxina");
        menuF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFActionPerformed(evt);
            }
        });
        menuDois.add(menuF);

        jMenuBar1.add(menuDois);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu1NdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu1NdActionPerformed
        // TODO add your handling code here:
        EscalaJanela escalaJanela = new EscalaJanela();
        escalaJanela.setVisible(true);
    }//GEN-LAST:event_menu1NdActionPerformed

    private void menuUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUmActionPerformed
        // TODO add your handling code here:
        // Cliquei no action performed desse por acidente.
        
    }//GEN-LAST:event_menuUmActionPerformed

    private void menuSegundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSegundoActionPerformed
        // TODO add your handling code here:
        SegundaJanela segundaJanela = new SegundaJanela();
        segundaJanela.setVisible(true);
    }//GEN-LAST:event_menuSegundoActionPerformed

    private void menuDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDoisActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menuDoisActionPerformed

    private void menuFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFActionPerformed
        // TODO add your handling code here:
        EscalaFaxina escalaFaxina = new EscalaFaxina();
        escalaFaxina.setVisible(true);
    }//GEN-LAST:event_menuFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menu1Nd;
    private javax.swing.JMenu menuDois;
    private javax.swing.JMenuItem menuF;
    private javax.swing.JMenuItem menuSegundo;
    private javax.swing.JMenu menuUm;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("soldier_3939761.png")));
    }
}
