/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.Toolkit;
/**
 *
 * @author Lenovo
 */
import javax.swing.ButtonGroup;
import java.awt.Dimension;

public class SegundaJanela extends javax.swing.JFrame {

    /**
     * Creates new form SegundaJanela
     */
    public SegundaJanela() {
        initComponents();
        setIcon();
        txtM7.setPreferredSize(new Dimension(74,29));
        panDois.setVisible(false);
        lblM7.setVisible(false);
        txtM7.setVisible(false);
        lblM8.setVisible(false);
        txtM8.setVisible(false);
        lblM9.setVisible(false);
        txtM9.setVisible(false);
        lblM10.setVisible(false);
        txtM10.setVisible(false);
        lblM11.setVisible(false);
        txtM11.setVisible(false);
        lblM12.setVisible(false);
        txtM12.setVisible(false);
        ButtonGroup buttonGroup = new ButtonGroup();
        rad6.setSelected(true);
        buttonGroup.add(rad6);
        buttonGroup.add(rad7);
        buttonGroup.add(rad8);
        buttonGroup.add(rad9);
        buttonGroup.add(rad10);
        buttonGroup.add(rad11);
        buttonGroup.add(rad12);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblM7 = new javax.swing.JLabel();
        txtM7 = new javax.swing.JTextField();
        lblM8 = new javax.swing.JLabel();
        txtM8 = new javax.swing.JTextField();
        lblM9 = new javax.swing.JLabel();
        txtM9 = new javax.swing.JTextField();
        lblM10 = new javax.swing.JLabel();
        txtM10 = new javax.swing.JTextField();
        lblM11 = new javax.swing.JLabel();
        txtM11 = new javax.swing.JTextField();
        lblM12 = new javax.swing.JLabel();
        txtM12 = new javax.swing.JTextField();
        rad10 = new javax.swing.JRadioButton();
        rad11 = new javax.swing.JRadioButton();
        rad12 = new javax.swing.JRadioButton();
        rad7 = new javax.swing.JRadioButton();
        rad8 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtM1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtM3 = new javax.swing.JTextField();
        txtM4 = new javax.swing.JTextField();
        txtM5 = new javax.swing.JTextField();
        rad9 = new javax.swing.JRadioButton();
        rad6 = new javax.swing.JRadioButton();
        panDois = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();
        lbl8 = new javax.swing.JLabel();
        lbl9 = new javax.swing.JLabel();
        lbl10 = new javax.swing.JLabel();
        lbl11 = new javax.swing.JLabel();
        lbl12 = new javax.swing.JLabel();
        lbl13 = new javax.swing.JLabel();
        lbl14 = new javax.swing.JLabel();
        lbl15 = new javax.swing.JLabel();
        lbl16 = new javax.swing.JLabel();
        lbl17 = new javax.swing.JLabel();
        lbl18 = new javax.swing.JLabel();
        lbl19 = new javax.swing.JLabel();
        lbl20 = new javax.swing.JLabel();
        lbl21 = new javax.swing.JLabel();
        lbl22 = new javax.swing.JLabel();
        lbl23 = new javax.swing.JLabel();
        lbl24 = new javax.swing.JLabel();
        lbl25 = new javax.swing.JLabel();
        lbl26 = new javax.swing.JLabel();
        lbl27 = new javax.swing.JLabel();
        lbl28 = new javax.swing.JLabel();
        lbl29 = new javax.swing.JLabel();
        lbl30 = new javax.swing.JLabel();
        lbl31 = new javax.swing.JLabel();
        lbl32 = new javax.swing.JLabel();
        lbl33 = new javax.swing.JLabel();
        lbl34 = new javax.swing.JLabel();
        lbl35 = new javax.swing.JLabel();
        lbl36 = new javax.swing.JLabel();
        lbl37 = new javax.swing.JLabel();
        lbl38 = new javax.swing.JLabel();
        lbl39 = new javax.swing.JLabel();
        lbl40 = new javax.swing.JLabel();
        lbl41 = new javax.swing.JLabel();
        lbl42 = new javax.swing.JLabel();
        lbl43 = new javax.swing.JLabel();
        lbl44 = new javax.swing.JLabel();
        lbl45 = new javax.swing.JLabel();
        lbl46 = new javax.swing.JLabel();
        lbl47 = new javax.swing.JLabel();
        lbl48 = new javax.swing.JLabel();
        lbl49 = new javax.swing.JLabel();
        lbl50 = new javax.swing.JLabel();
        lbl51 = new javax.swing.JLabel();
        lbl52 = new javax.swing.JLabel();
        lbl53 = new javax.swing.JLabel();
        lbl54 = new javax.swing.JLabel();
        lbl55 = new javax.swing.JLabel();
        lbl56 = new javax.swing.JLabel();
        lbl57 = new javax.swing.JLabel();
        lbl58 = new javax.swing.JLabel();
        lbl59 = new javax.swing.JLabel();
        lbl60 = new javax.swing.JLabel();
        lbl61 = new javax.swing.JLabel();
        lbl62 = new javax.swing.JLabel();
        btnEx2 = new javax.swing.JButton();
        txtM2 = new javax.swing.JTextField();
        txtM6 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Escala de serviço com 2 por dia.");
        setResizable(false);

        lblM7.setText("07º  Militar");

        lblM8.setText("08º Militar");

        lblM9.setText("09º Militar");

        lblM10.setText("10º Militar");

        lblM11.setText("11º Militar");

        lblM12.setText("12º Militar");

        rad10.setText("10 Militares");
        rad10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad10ActionPerformed(evt);
            }
        });

        rad11.setText("11 Militares");
        rad11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad11ActionPerformed(evt);
            }
        });

        rad12.setText("12 Militares");
        rad12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad12ActionPerformed(evt);
            }
        });

        rad7.setText("07 Militares");
        rad7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad7ActionPerformed(evt);
            }
        });

        rad8.setText("08 Militares");
        rad8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad8ActionPerformed(evt);
            }
        });

        jLabel1.setText("01º Militar");

        jLabel6.setText("02º Militar");

        jLabel7.setText("03º Militar");

        jLabel8.setText("04º Militar");

        jLabel9.setText("05º Militar");

        jLabel10.setText("06º Militar");

        rad9.setText("09 Militares");
        rad9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad9ActionPerformed(evt);
            }
        });

        rad6.setText("06 Militares");
        rad6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad6ActionPerformed(evt);
            }
        });

        panDois.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("01-");

        jLabel3.setText("02-");

        jLabel4.setText("03-");

        jLabel5.setText("04-");

        jLabel11.setText("05-");

        jLabel12.setText("06-");

        jLabel13.setText("07-");

        jLabel14.setText("08-");

        jLabel15.setText("09-");

        jLabel16.setText("10-");

        jLabel17.setText("11-");

        jLabel18.setText("12-");

        jLabel19.setText("13-");

        jLabel20.setText("14-");

        jLabel21.setText("15-");

        jLabel22.setText("16-");

        jLabel23.setText("17-");

        jLabel24.setText("18-");

        jLabel25.setText("19-");

        jLabel26.setText("20-");

        jLabel27.setText("21-");

        jLabel28.setText("22-");

        jLabel29.setText("23-");

        jLabel30.setText("24-");

        jLabel31.setText("25-");

        jLabel32.setText("26-");

        jLabel33.setText("27-");

        jLabel34.setText("28-");

        jLabel35.setText("29-");

        jLabel36.setText("30-");

        jLabel37.setText("31-");

        lbl1.setText("jLabel38");

        lbl2.setText("jLabel39");

        lbl3.setText("jLabel40");

        lbl4.setText("jLabel41");

        lbl5.setText("jLabel42");

        lbl6.setText("jLabel43");

        lbl7.setText("jLabel44");

        lbl8.setText("jLabel45");

        lbl9.setText("jLabel46");

        lbl10.setText("jLabel47");

        lbl11.setText("jLabel48");

        lbl12.setText("jLabel49");

        lbl13.setText("jLabel50");

        lbl14.setText("jLabel51");

        lbl15.setText("jLabel52");

        lbl16.setText("jLabel53");

        lbl17.setText("jLabel54");

        lbl18.setText("jLabel55");

        lbl19.setText("jLabel56");

        lbl20.setText("jLabel57");

        lbl21.setText("jLabel58");

        lbl22.setText("jLabel59");

        lbl23.setText("jLabel60");

        lbl24.setText("jLabel61");

        lbl25.setText("jLabel62");

        lbl26.setText("jLabel63");

        lbl27.setText("jLabel64");

        lbl28.setText("jLabel65");

        lbl29.setText("jLabel66");

        lbl30.setText("jLabel67");

        lbl31.setText("jLabel68");

        lbl32.setText("jLabel69");

        lbl33.setText("jLabel70");

        lbl34.setText("jLabel71");

        lbl35.setText("jLabel72");

        lbl36.setText("jLabel73");

        lbl37.setText("jLabel74");

        lbl38.setText("jLabel75");

        lbl39.setText("jLabel76");

        lbl40.setText("jLabel77");

        lbl41.setText("jLabel78");

        lbl42.setText("jLabel79");

        lbl43.setText("jLabel80");

        lbl44.setText("jLabel81");

        lbl45.setText("jLabel82");

        lbl46.setText("jLabel83");

        lbl47.setText("jLabel84");

        lbl48.setText("jLabel85");

        lbl49.setText("jLabel86");

        lbl50.setText("jLabel87");

        lbl51.setText("jLabel88");

        lbl52.setText("jLabel89");

        lbl53.setText("jLabel90");

        lbl54.setText("jLabel91");

        lbl55.setText("jLabel92");

        lbl56.setText("jLabel93");

        lbl57.setText("jLabel94");

        lbl58.setText("jLabel95");

        lbl59.setText("jLabel96");

        lbl60.setText("jLabel97");

        lbl61.setText("jLabel98");

        lbl62.setText("jLabel99");

        javax.swing.GroupLayout panDoisLayout = new javax.swing.GroupLayout(panDois);
        panDois.setLayout(panDoisLayout);
        panDoisLayout.setHorizontalGroup(
            panDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDoisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panDoisLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl4))
                    .addGroup(panDoisLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl6))
                    .addGroup(panDoisLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl8))
                    .addGroup(panDoisLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl10))
                    .addGroup(panDoisLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl12))
                    .addGroup(panDoisLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl14))
                    .addGroup(panDoisLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl16))
                    .addGroup(panDoisLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl18))
                    .addGroup(panDoisLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl20))
                    .addGroup(panDoisLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl2)))
                .addGap(18, 18, 18)
                .addGroup(panDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panDoisLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl24))
                    .addGroup(panDoisLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl26))
                    .addGroup(panDoisLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl28))
                    .addGroup(panDoisLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl30))
                    .addGroup(panDoisLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl32))
                    .addGroup(panDoisLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl34))
                    .addGroup(panDoisLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl36))
                    .addGroup(panDoisLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl38))
                    .addGroup(panDoisLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl40))
                    .addGroup(panDoisLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl22)))
                .addGap(18, 18, 18)
                .addGroup(panDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panDoisLayout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl59)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl60))
                    .addGroup(panDoisLayout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl57)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl58))
                    .addGroup(panDoisLayout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl55)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl56))
                    .addGroup(panDoisLayout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl53)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl54))
                    .addGroup(panDoisLayout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl51)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl52))
                    .addGroup(panDoisLayout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl49)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl50))
                    .addGroup(panDoisLayout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl47)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl48))
                    .addGroup(panDoisLayout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl45)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl46))
                    .addGroup(panDoisLayout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl43)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl44))
                    .addGroup(panDoisLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl42)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl61)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl62)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panDoisLayout.setVerticalGroup(
            panDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDoisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel17)
                    .addComponent(jLabel27)
                    .addComponent(jLabel37)
                    .addComponent(lbl1)
                    .addComponent(lbl2)
                    .addComponent(lbl21)
                    .addComponent(lbl22)
                    .addComponent(lbl41)
                    .addComponent(lbl42)
                    .addComponent(lbl61)
                    .addComponent(lbl62))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel18)
                    .addComponent(jLabel28)
                    .addComponent(lbl3)
                    .addComponent(lbl4)
                    .addComponent(lbl23)
                    .addComponent(lbl24)
                    .addComponent(lbl43)
                    .addComponent(lbl44))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel19)
                    .addComponent(jLabel29)
                    .addComponent(lbl5)
                    .addComponent(lbl6)
                    .addComponent(lbl25)
                    .addComponent(lbl26)
                    .addComponent(lbl45)
                    .addComponent(lbl46))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel20)
                    .addComponent(jLabel30)
                    .addComponent(lbl7)
                    .addComponent(lbl8)
                    .addComponent(lbl27)
                    .addComponent(lbl28)
                    .addComponent(lbl47)
                    .addComponent(lbl48))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel21)
                    .addComponent(jLabel31)
                    .addComponent(lbl9)
                    .addComponent(lbl10)
                    .addComponent(lbl29)
                    .addComponent(lbl30)
                    .addComponent(lbl49)
                    .addComponent(lbl50))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel22)
                    .addComponent(jLabel32)
                    .addComponent(lbl11)
                    .addComponent(lbl12)
                    .addComponent(lbl31)
                    .addComponent(lbl32)
                    .addComponent(lbl51)
                    .addComponent(lbl52))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel23)
                    .addComponent(jLabel33)
                    .addComponent(lbl13)
                    .addComponent(lbl14)
                    .addComponent(lbl33)
                    .addComponent(lbl34)
                    .addComponent(lbl53)
                    .addComponent(lbl54))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel24)
                    .addComponent(jLabel34)
                    .addComponent(lbl15)
                    .addComponent(lbl16)
                    .addComponent(lbl35)
                    .addComponent(lbl36)
                    .addComponent(lbl55)
                    .addComponent(lbl56))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel25)
                    .addComponent(jLabel35)
                    .addComponent(lbl17)
                    .addComponent(lbl18)
                    .addComponent(lbl37)
                    .addComponent(lbl38)
                    .addComponent(lbl57)
                    .addComponent(lbl58))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel26)
                    .addComponent(jLabel36)
                    .addComponent(lbl19)
                    .addComponent(lbl20)
                    .addComponent(lbl39)
                    .addComponent(lbl40)
                    .addComponent(lbl59)
                    .addComponent(lbl60))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        btnEx2.setBackground(new java.awt.Color(204, 0, 0));
        btnEx2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEx2.setForeground(new java.awt.Color(255, 255, 255));
        btnEx2.setText("Executar");
        btnEx2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEx2ActionPerformed(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel38.setText("Militares na escala");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(panDois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 155, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtM3)
                                    .addComponent(txtM2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtM6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtM5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtM4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtM1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblM7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblM8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblM9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblM10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblM11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblM12, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtM9)
                            .addComponent(txtM10, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtM11, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtM12, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtM8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtM7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rad6)
                                        .addComponent(rad10)
                                        .addComponent(rad11)
                                        .addComponent(rad12)
                                        .addComponent(rad7)
                                        .addComponent(rad8)
                                        .addComponent(rad9))
                                    .addGap(13, 13, 13))
                                .addComponent(btnEx2, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel38, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblM7)
                            .addComponent(txtM7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(txtM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblM8)
                            .addComponent(txtM8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txtM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblM9)
                            .addComponent(txtM9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txtM3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblM10)
                            .addComponent(txtM10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txtM4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblM11)
                            .addComponent(txtM11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(txtM5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblM12)
                            .addComponent(txtM12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(txtM6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addGap(18, 18, 18)
                        .addComponent(rad6)
                        .addGap(18, 18, 18)
                        .addComponent(rad7)
                        .addGap(18, 18, 18)
                        .addComponent(rad8)
                        .addGap(18, 18, 18)
                        .addComponent(rad9)
                        .addGap(18, 18, 18)
                        .addComponent(rad10)
                        .addGap(18, 18, 18)
                        .addComponent(rad11)
                        .addGap(18, 18, 18)
                        .addComponent(rad12)
                        .addGap(18, 18, 18)
                        .addComponent(btnEx2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(panDois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEx2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEx2ActionPerformed
        // TODO add your handling code here:
        panDois.setVisible(true);
        String milico1 = (txtM1.getText());
        String milico2 = (txtM2.getText());
        String milico3 = (txtM3.getText());
        String milico4 = (txtM4.getText());
        String milico5 = (txtM5.getText());
        String milico6 = (txtM6.getText());
        lbl1.setText(milico1);
        lbl2.setText(milico2);
        lbl3.setText(milico3);
        lbl4.setText(milico4);
        lbl5.setText(milico5);
        lbl6.setText(milico6);
        lbl7.setText(milico1);
        lbl8.setText(milico2);
        lbl9.setText(milico3);
        lbl10.setText(milico4);
        lbl11.setText(milico5);
        lbl12.setText(milico6);
        lbl13.setText(milico1);
        lbl14.setText(milico2);
        lbl15.setText(milico3);
        lbl16.setText(milico4);
        lbl17.setText(milico5);
        lbl18.setText(milico6);
        lbl19.setText(milico1);
        lbl20.setText(milico2);
        lbl21.setText(milico3);
        lbl22.setText(milico4);
        lbl23.setText(milico5);
        lbl24.setText(milico6);
        lbl25.setText(milico1);
        lbl26.setText(milico2);
        lbl27.setText(milico3);
        lbl28.setText(milico4);
        lbl29.setText(milico5);
        lbl30.setText(milico6);
        lbl31.setText(milico1);
        lbl32.setText(milico2);
        lbl33.setText(milico3);
        lbl34.setText(milico4);
        lbl35.setText(milico5);
        lbl36.setText(milico6);
        lbl37.setText(milico1);
        lbl38.setText(milico2);
        lbl39.setText(milico3);
        lbl40.setText(milico4);
        lbl41.setText(milico5);
        lbl42.setText(milico6);
        lbl43.setText(milico1);
        lbl44.setText(milico2);
        lbl45.setText(milico3);
        lbl46.setText(milico4);
        lbl47.setText(milico5);
        lbl48.setText(milico6);
        lbl49.setText(milico1);
        lbl50.setText(milico2);
        lbl51.setText(milico3);
        lbl52.setText(milico4);
        lbl53.setText(milico5);
        lbl54.setText(milico6);
        lbl55.setText(milico1);
        lbl56.setText(milico2);
        lbl57.setText(milico3);
        lbl58.setText(milico4);
        lbl59.setText(milico5);
        lbl60.setText(milico6);
        lbl61.setText(milico1);
        lbl62.setText(milico2);
        if(rad7.isSelected()){
            String milico7 = (txtM7.getText());
            lbl1.setText(milico1);
            lbl2.setText(milico2);
            lbl3.setText(milico3);
            lbl4.setText(milico4);
            lbl5.setText(milico5);
            lbl6.setText(milico6);
            lbl7.setText(milico7);
            lbl8.setText(milico1);
            lbl9.setText(milico2);
            lbl10.setText(milico3);
            lbl11.setText(milico4);
            lbl12.setText(milico5);
            lbl13.setText(milico6);
            lbl14.setText(milico7);
            lbl15.setText(milico1);
            lbl16.setText(milico2);
            lbl17.setText(milico3);
            lbl18.setText(milico4);
            lbl19.setText(milico5);
            lbl20.setText(milico6);
            lbl21.setText(milico7);
            lbl22.setText(milico1);
            lbl23.setText(milico2);
            lbl24.setText(milico3);
            lbl25.setText(milico4);
            lbl26.setText(milico5);
            lbl27.setText(milico6);
            lbl28.setText(milico7);
            lbl29.setText(milico1);
            lbl30.setText(milico2);
            lbl31.setText(milico3);
            lbl32.setText(milico4);
            lbl33.setText(milico5);
            lbl34.setText(milico6);
            lbl35.setText(milico7);
            lbl36.setText(milico1);
            lbl37.setText(milico2);
            lbl38.setText(milico3);
            lbl39.setText(milico4);
            lbl40.setText(milico5);
            lbl41.setText(milico6);
            lbl42.setText(milico7);
            lbl43.setText(milico1);
            lbl44.setText(milico2);
            lbl45.setText(milico3);
            lbl46.setText(milico4);
            lbl47.setText(milico5);
            lbl48.setText(milico6);
            lbl49.setText(milico7);
            lbl50.setText(milico1);
            lbl51.setText(milico2);
            lbl52.setText(milico3);
            lbl53.setText(milico4);
            lbl54.setText(milico5);
            lbl55.setText(milico6);
            lbl56.setText(milico7);
            lbl57.setText(milico1);
            lbl58.setText(milico2);
            lbl59.setText(milico3);
            lbl60.setText(milico4);
            lbl61.setText(milico5);
            lbl62.setText(milico6);
        }
        if(rad8.isSelected()){
            String milico7 = (txtM7.getText());
            String milico8 = (txtM8.getText());
            lbl1.setText(milico1);
            lbl2.setText(milico2);
            lbl3.setText(milico3);
            lbl4.setText(milico4);
            lbl5.setText(milico5);
            lbl6.setText(milico6);
            lbl7.setText(milico7);
            lbl8.setText(milico8);
            lbl9.setText(milico1);
            lbl10.setText(milico2);
            lbl11.setText(milico3);
            lbl12.setText(milico4);
            lbl13.setText(milico5);
            lbl14.setText(milico6);
            lbl15.setText(milico7);
            lbl16.setText(milico8);
            lbl17.setText(milico1);
            lbl18.setText(milico2);
            lbl19.setText(milico3);
            lbl20.setText(milico4);
            lbl21.setText(milico5);
            lbl22.setText(milico6);
            lbl23.setText(milico7);
            lbl24.setText(milico8);
            lbl25.setText(milico1);
            lbl26.setText(milico2);
            lbl27.setText(milico3);
            lbl28.setText(milico4);
            lbl29.setText(milico5);
            lbl30.setText(milico6);
            lbl31.setText(milico7);
            lbl32.setText(milico8);
            lbl33.setText(milico1);
            lbl34.setText(milico2);
            lbl35.setText(milico3);
            lbl36.setText(milico4);
            lbl37.setText(milico5);
            lbl38.setText(milico6);
            lbl39.setText(milico7);
            lbl40.setText(milico8);
            lbl41.setText(milico1);
            lbl42.setText(milico2);
            lbl43.setText(milico3);
            lbl44.setText(milico4);
            lbl45.setText(milico5);
            lbl46.setText(milico6);
            lbl47.setText(milico7);
            lbl48.setText(milico8);
            lbl49.setText(milico1);
            lbl50.setText(milico2);
            lbl51.setText(milico3);
            lbl52.setText(milico4);
            lbl53.setText(milico5);
            lbl54.setText(milico6);
            lbl55.setText(milico7);
            lbl56.setText(milico8);
            lbl57.setText(milico1);
            lbl58.setText(milico2);
            lbl59.setText(milico3);
            lbl60.setText(milico4);
            lbl61.setText(milico5);
            lbl62.setText(milico6);            
        }
        if(rad9.isSelected()){
            String milico7 = (txtM7.getText());
            String milico8 = (txtM8.getText());
            String milico9 = (txtM9.getText());
            lbl1.setText(milico1);
            lbl2.setText(milico2);
            lbl3.setText(milico3);
            lbl4.setText(milico4);
            lbl5.setText(milico5);
            lbl6.setText(milico6);
            lbl7.setText(milico7);
            lbl8.setText(milico8);
            lbl9.setText(milico9);
            lbl10.setText(milico1);
            lbl11.setText(milico2);
            lbl12.setText(milico3);
            lbl13.setText(milico4);
            lbl14.setText(milico5);
            lbl15.setText(milico6);
            lbl16.setText(milico7);
            lbl17.setText(milico8);
            lbl18.setText(milico9);
            lbl19.setText(milico1);
            lbl20.setText(milico2);
            lbl21.setText(milico3);
            lbl22.setText(milico4);
            lbl23.setText(milico5);
            lbl24.setText(milico6);
            lbl25.setText(milico7);
            lbl26.setText(milico8);
            lbl27.setText(milico9);
            lbl28.setText(milico1);
            lbl29.setText(milico2);
            lbl30.setText(milico3);
            lbl31.setText(milico4);
            lbl32.setText(milico5);
            lbl33.setText(milico6);
            lbl34.setText(milico7);
            lbl35.setText(milico8);
            lbl36.setText(milico9);
            lbl37.setText(milico1);
            lbl38.setText(milico2);
            lbl39.setText(milico3);
            lbl40.setText(milico4);
            lbl41.setText(milico5);
            lbl42.setText(milico6);
            lbl43.setText(milico7);
            lbl44.setText(milico8);
            lbl45.setText(milico9);
            lbl46.setText(milico1);
            lbl47.setText(milico2);
            lbl48.setText(milico3);
            lbl49.setText(milico4);
            lbl50.setText(milico5);
            lbl51.setText(milico6);
            lbl52.setText(milico7);
            lbl53.setText(milico8);
            lbl54.setText(milico9);
            lbl55.setText(milico1);
            lbl56.setText(milico2);
            lbl57.setText(milico3);
            lbl58.setText(milico4);
            lbl59.setText(milico5);
            lbl60.setText(milico6);
            lbl61.setText(milico7);
            lbl62.setText(milico8);           
        }
        if(rad10.isSelected()){
            String milico7 = (txtM7.getText());
            String milico8 = (txtM8.getText());
            String milico9 = (txtM9.getText());
            String milico10 = (txtM10.getText());
            lbl1.setText(milico1);
            lbl2.setText(milico2);
            lbl3.setText(milico3);
            lbl4.setText(milico4);
            lbl5.setText(milico5);
            lbl6.setText(milico6);
            lbl7.setText(milico7);
            lbl8.setText(milico8);
            lbl9.setText(milico9);
            lbl10.setText(milico10);
            lbl11.setText(milico1);
            lbl12.setText(milico2);
            lbl13.setText(milico3);
            lbl14.setText(milico4);
            lbl15.setText(milico5);
            lbl16.setText(milico6);
            lbl17.setText(milico7);
            lbl18.setText(milico8);
            lbl19.setText(milico9);
            lbl20.setText(milico10);
            lbl21.setText(milico1);
            lbl22.setText(milico2);
            lbl23.setText(milico3);
            lbl24.setText(milico4);
            lbl25.setText(milico5);
            lbl26.setText(milico6);
            lbl27.setText(milico7);
            lbl28.setText(milico8);
            lbl29.setText(milico9);
            lbl30.setText(milico10);
            lbl31.setText(milico1);
            lbl32.setText(milico2);
            lbl33.setText(milico3);
            lbl34.setText(milico4);
            lbl35.setText(milico5);
            lbl36.setText(milico6);
            lbl37.setText(milico7);
            lbl38.setText(milico8);
            lbl39.setText(milico9);
            lbl40.setText(milico10);
            lbl41.setText(milico1);
            lbl42.setText(milico2);
            lbl43.setText(milico3);
            lbl44.setText(milico4);
            lbl45.setText(milico5);
            lbl46.setText(milico6);
            lbl47.setText(milico7);
            lbl48.setText(milico8);
            lbl49.setText(milico9);
            lbl50.setText(milico10);
            lbl51.setText(milico1);
            lbl52.setText(milico2);
            lbl53.setText(milico3);
            lbl54.setText(milico4);
            lbl55.setText(milico5);
            lbl56.setText(milico6);
            lbl57.setText(milico7);
            lbl58.setText(milico8);
            lbl59.setText(milico9);
            lbl60.setText(milico10);
            lbl61.setText(milico1);
            lbl62.setText(milico2);
        }
        if(rad11.isSelected()){
            String milico7 = (txtM7.getText());
            String milico8 = (txtM8.getText());
            String milico9 = (txtM9.getText());
            String milico10 = (txtM10.getText());
            String milico11 = (txtM11.getText());
            lbl1.setText(milico1);
            lbl2.setText(milico2);
            lbl3.setText(milico3);
            lbl4.setText(milico4);
            lbl5.setText(milico5);
            lbl6.setText(milico6);
            lbl7.setText(milico7);
            lbl8.setText(milico8);
            lbl9.setText(milico9);
            lbl10.setText(milico10);
            lbl11.setText(milico11);
            lbl12.setText(milico1);
            lbl13.setText(milico2);
            lbl14.setText(milico3);
            lbl15.setText(milico4);
            lbl16.setText(milico5);
            lbl17.setText(milico6);
            lbl18.setText(milico7);
            lbl19.setText(milico8);
            lbl20.setText(milico9);
            lbl21.setText(milico10);
            lbl22.setText(milico11);
            lbl23.setText(milico1);
            lbl24.setText(milico2);
            lbl25.setText(milico3);
            lbl26.setText(milico4);
            lbl27.setText(milico5);
            lbl28.setText(milico6);
            lbl29.setText(milico7);
            lbl30.setText(milico8);
            lbl31.setText(milico9);
            lbl32.setText(milico10);
            lbl33.setText(milico11);
            lbl34.setText(milico1);
            lbl35.setText(milico2);
            lbl36.setText(milico3);
            lbl37.setText(milico4);
            lbl38.setText(milico5);
            lbl39.setText(milico6);
            lbl40.setText(milico7);
            lbl41.setText(milico8);
            lbl42.setText(milico9);
            lbl43.setText(milico10);
            lbl44.setText(milico11);
            lbl45.setText(milico1);
            lbl46.setText(milico2);
            lbl47.setText(milico3);
            lbl48.setText(milico4);
            lbl49.setText(milico5);
            lbl50.setText(milico6);
            lbl51.setText(milico7);
            lbl52.setText(milico8);
            lbl53.setText(milico9);
            lbl54.setText(milico10);
            lbl55.setText(milico11);
            lbl56.setText(milico1);
            lbl57.setText(milico2);
            lbl58.setText(milico3);
            lbl59.setText(milico4);
            lbl60.setText(milico5);
            lbl61.setText(milico6);
            lbl62.setText(milico7);
        }
        if(rad12.isSelected()){
            String milico7 = (txtM7.getText());
            String milico8 = (txtM8.getText());
            String milico9 = (txtM9.getText());
            String milico10 = (txtM10.getText());
            String milico11 = (txtM11.getText());
            String milico12 = (txtM12.getText());
            lbl1.setText(milico1);
            lbl2.setText(milico2);
            lbl3.setText(milico3);
            lbl4.setText(milico4);
            lbl5.setText(milico5);
            lbl6.setText(milico6);
            lbl7.setText(milico7);
            lbl8.setText(milico8);
            lbl9.setText(milico9);
            lbl10.setText(milico10);
            lbl11.setText(milico11);
            lbl12.setText(milico12);
            lbl13.setText(milico1);
            lbl14.setText(milico2);
            lbl15.setText(milico3);
            lbl16.setText(milico4);
            lbl17.setText(milico5);
            lbl18.setText(milico6);
            lbl19.setText(milico7);
            lbl20.setText(milico8);
            lbl21.setText(milico9);
            lbl22.setText(milico10);
            lbl23.setText(milico11);
            lbl24.setText(milico12);
            lbl25.setText(milico1);
            lbl26.setText(milico2);
            lbl27.setText(milico3);
            lbl28.setText(milico4);
            lbl29.setText(milico5);
            lbl30.setText(milico6);
            lbl31.setText(milico7);
            lbl32.setText(milico8);
            lbl33.setText(milico9);
            lbl34.setText(milico10);
            lbl35.setText(milico11);
            lbl36.setText(milico12);
            lbl37.setText(milico1);
            lbl38.setText(milico2);
            lbl39.setText(milico3);
            lbl40.setText(milico4);
            lbl41.setText(milico5);
            lbl42.setText(milico6);
            lbl43.setText(milico7);
            lbl44.setText(milico8);
            lbl45.setText(milico9);
            lbl46.setText(milico10);
            lbl47.setText(milico11);
            lbl48.setText(milico12);
            lbl49.setText(milico1);
            lbl50.setText(milico2);
            lbl51.setText(milico3);
            lbl52.setText(milico4);
            lbl53.setText(milico5);
            lbl54.setText(milico6);
            lbl55.setText(milico7);
            lbl56.setText(milico8);
            lbl57.setText(milico9);
            lbl58.setText(milico10);
            lbl59.setText(milico11);
            lbl60.setText(milico12);
            lbl61.setText(milico1);
            lbl62.setText(milico2);
        }
    }//GEN-LAST:event_btnEx2ActionPerformed

    private void rad6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad6ActionPerformed
        // TODO add your handling code here:
        lblM7.setVisible(false);
        txtM7.setVisible(false);
        lblM8.setVisible(false);
        txtM8.setVisible(false);
        lblM9.setVisible(false);
        txtM9.setVisible(false);
        lblM10.setVisible(false);
        txtM10.setVisible(false);
        lblM11.setVisible(false);
        txtM11.setVisible(false);
        lblM12.setVisible(false);
        txtM12.setVisible(false);
    }//GEN-LAST:event_rad6ActionPerformed

    private void rad7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad7ActionPerformed
        // TODO add your handling code here:
        lblM7.setVisible(true);
        txtM7.setVisible(true);
        lblM8.setVisible(false);
        txtM8.setVisible(false);
        lblM9.setVisible(false);
        txtM9.setVisible(false);
        lblM10.setVisible(false);
        txtM10.setVisible(false);
        lblM11.setVisible(false);
        txtM11.setVisible(false);
        lblM12.setVisible(false);
        txtM12.setVisible(false);
    }//GEN-LAST:event_rad7ActionPerformed

    private void rad8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad8ActionPerformed
        // TODO add your handling code here:
        lblM7.setVisible(true);
        txtM7.setVisible(true);
        lblM8.setVisible(true);
        txtM8.setVisible(true);
        lblM9.setVisible(false);
        txtM9.setVisible(false);
        lblM10.setVisible(false);
        txtM10.setVisible(false);
        lblM11.setVisible(false);
        txtM11.setVisible(false);
        lblM12.setVisible(false);
        txtM12.setVisible(false);
    }//GEN-LAST:event_rad8ActionPerformed

    private void rad9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad9ActionPerformed
        // TODO add your handling code here:
        lblM7.setVisible(true);
        txtM7.setVisible(true);
        lblM8.setVisible(true);
        txtM8.setVisible(true);
        lblM9.setVisible(true);
        txtM9.setVisible(true);
        lblM10.setVisible(false);
        txtM10.setVisible(false);
        lblM11.setVisible(false);
        txtM11.setVisible(false);
        lblM12.setVisible(false);
        txtM12.setVisible(false);
    }//GEN-LAST:event_rad9ActionPerformed

    private void rad10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad10ActionPerformed
        // TODO add your handling code here:
        lblM7.setVisible(true);
        txtM7.setVisible(true);
        lblM8.setVisible(true);
        txtM8.setVisible(true);
        lblM9.setVisible(true);
        txtM9.setVisible(true);
        lblM10.setVisible(true);
        txtM10.setVisible(true);
        lblM11.setVisible(false);
        txtM11.setVisible(false);
        lblM12.setVisible(false);
        txtM12.setVisible(false);
        
    }//GEN-LAST:event_rad10ActionPerformed

    private void rad11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad11ActionPerformed
        // TODO add your handling code here:
        lblM7.setVisible(true);
        txtM7.setVisible(true);
        lblM8.setVisible(true);
        txtM8.setVisible(true);
        lblM9.setVisible(true);
        txtM9.setVisible(true);
        lblM10.setVisible(true);
        txtM10.setVisible(true);
        lblM11.setVisible(true);
        txtM11.setVisible(true);
        lblM12.setVisible(false);
        txtM12.setVisible(false);
    }//GEN-LAST:event_rad11ActionPerformed

    private void rad12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad12ActionPerformed
        // TODO add your handling code here:
        lblM7.setVisible(true);
        txtM7.setVisible(true);
        lblM8.setVisible(true);
        txtM8.setVisible(true);
        lblM9.setVisible(true);
        txtM9.setVisible(true);
        lblM10.setVisible(true);
        txtM10.setVisible(true);
        lblM11.setVisible(true);
        txtM11.setVisible(true);
        lblM12.setVisible(true);
        txtM12.setVisible(true);
    }//GEN-LAST:event_rad12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SegundaJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SegundaJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SegundaJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SegundaJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SegundaJanela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEx2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl11;
    private javax.swing.JLabel lbl12;
    private javax.swing.JLabel lbl13;
    private javax.swing.JLabel lbl14;
    private javax.swing.JLabel lbl15;
    private javax.swing.JLabel lbl16;
    private javax.swing.JLabel lbl17;
    private javax.swing.JLabel lbl18;
    private javax.swing.JLabel lbl19;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl20;
    private javax.swing.JLabel lbl21;
    private javax.swing.JLabel lbl22;
    private javax.swing.JLabel lbl23;
    private javax.swing.JLabel lbl24;
    private javax.swing.JLabel lbl25;
    private javax.swing.JLabel lbl26;
    private javax.swing.JLabel lbl27;
    private javax.swing.JLabel lbl28;
    private javax.swing.JLabel lbl29;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl30;
    private javax.swing.JLabel lbl31;
    private javax.swing.JLabel lbl32;
    private javax.swing.JLabel lbl33;
    private javax.swing.JLabel lbl34;
    private javax.swing.JLabel lbl35;
    private javax.swing.JLabel lbl36;
    private javax.swing.JLabel lbl37;
    private javax.swing.JLabel lbl38;
    private javax.swing.JLabel lbl39;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl40;
    private javax.swing.JLabel lbl41;
    private javax.swing.JLabel lbl42;
    private javax.swing.JLabel lbl43;
    private javax.swing.JLabel lbl44;
    private javax.swing.JLabel lbl45;
    private javax.swing.JLabel lbl46;
    private javax.swing.JLabel lbl47;
    private javax.swing.JLabel lbl48;
    private javax.swing.JLabel lbl49;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl50;
    private javax.swing.JLabel lbl51;
    private javax.swing.JLabel lbl52;
    private javax.swing.JLabel lbl53;
    private javax.swing.JLabel lbl54;
    private javax.swing.JLabel lbl55;
    private javax.swing.JLabel lbl56;
    private javax.swing.JLabel lbl57;
    private javax.swing.JLabel lbl58;
    private javax.swing.JLabel lbl59;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl60;
    private javax.swing.JLabel lbl61;
    private javax.swing.JLabel lbl62;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl9;
    private javax.swing.JLabel lblM10;
    private javax.swing.JLabel lblM11;
    private javax.swing.JLabel lblM12;
    private javax.swing.JLabel lblM7;
    private javax.swing.JLabel lblM8;
    private javax.swing.JLabel lblM9;
    private javax.swing.JPanel panDois;
    private javax.swing.JRadioButton rad10;
    private javax.swing.JRadioButton rad11;
    private javax.swing.JRadioButton rad12;
    private javax.swing.JRadioButton rad6;
    private javax.swing.JRadioButton rad7;
    private javax.swing.JRadioButton rad8;
    private javax.swing.JRadioButton rad9;
    private javax.swing.JTextField txtM1;
    private javax.swing.JTextField txtM10;
    private javax.swing.JTextField txtM11;
    private javax.swing.JTextField txtM12;
    private javax.swing.JTextField txtM2;
    private javax.swing.JTextField txtM3;
    private javax.swing.JTextField txtM4;
    private javax.swing.JTextField txtM5;
    private javax.swing.JTextField txtM6;
    private javax.swing.JTextField txtM7;
    private javax.swing.JTextField txtM8;
    private javax.swing.JTextField txtM9;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("soldier_3939761.png")));
    }
}
